# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: microdrop.default-ui-plugins
{% if GIT_DESCRIBE_NUMBER > '0' %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}.post{{ GIT_DESCRIBE_NUMBER }}
{% else %}
  version: {{ GIT_DESCRIBE_TAG[1:] }}
{% endif %}

build:
  number: 0
  script: python -m mpm.bin.build

requirements:
  build:
    - microdrop-plugin-manager >=0.11

about:
  home: https://github.com/Lucaszw/default-ui-plugins
  license: GPL
